<?php

use yii\helpers\Html;
use yii\grid\GridView;
use backend\models\Category;
use yii\helpers\ArrayHelper;

$this->title = 'Cài đặt khác';
$this->params['breadcrumbs'][] = $this->title;
$this->params['breadcrumbs']['description_page'] = 'Cài đặt khác';
$controller = Yii::$app->controller->id;
$this->params['breadcrumbs']['icon_page'] = 'fa-tag';
?>
<div class="projects-index">

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    
    <div class="card mb-g">
        <div class="card-body table-responsive">
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <!-- <img src="https://phavico.com/images/page/map.png" usemap="#image-map">

            <map name="image-map">
                <area target="_blank" alt="here" title="here" href="https://phavico.com/images/page/map.png" coords="0,0,20" shape="circle">
                <area target="" alt="" title="" href="" coords="" shape="0">
            </map> -->
            <p class="map-x">
                <span class="loca_0">0</span>
                <span class="loca_2">27</span>
                <span class="loca_2">53</span>
                <span class="loca_2">80</span>
                <span class="loca_3">107</span>
                <span class="loca_3">134</span>
                <span class="loca_3">161</span>
                <span class="loca_3">188</span>
                <span class="loca_3">215</span>
                <span class="loca_4">242</span>
                <span class="loca_4">268</span>
                <span class="loca_4">295</span>
                <span class="loca_4">322</span>
                <span class="loca_4">349</span>
                <span class="loca_4">376</span>
                <span class="loca_5">403</span>
                <span class="loca_5">430</span>
                <span class="loca_5">456</span>
                <span class="loca_5">483</span>
                <span class="loca_5">510</span>
                <span class="loca_5">537</span>
            </p>
            <div class="location_map">
                <img src="https://phavico.com/images/page/map.png">    
                <table class="grid_table table table-bordered">
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                    <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                </table>
                <div id='pin-1' class="box" >
                    <div class="pin-text">
                        <h4>Hà Nội</h4>
                        <p>Số 7, P. Thiền Quang - 0999.xxx.xxx</p>
                    </div>
                </div>
            </div>
            <style>
                .map-x {
  margin-bottom: 0;
  margin-left: 13px;
  font-size: 10px;
  font-weight: 500;
}
.loca_0 {
  margin-right: 9px;
}
.loca_2 {
  margin-left: 12px;
}
.loca_3, .loca_5 {
  margin-left: 8px;
}
.loca_4 {
  margin-left: 6px;
}
                .table-bordered th, .table-bordered td {
                    border: 1px solid #403e3e52;

                }
                .box:hover > .pin-text {
                    display: block;
                }
                .location_map {
                    width: 537px;
                    height: 572px;
                    position: relative;
                    margin-top: 5px;
                    margin-left: 20px
                }
                .grid_table {
                    position: absolute;
                    top: 0;
                    left:0;
                }
                .grid_table td {padding:25px 0 0 0}
                .pin-text {
                    position: absolute;
                    top: 50%;
                    transform: translateY(-50%);
                    left: 100%;
                    white-space: nowrap;
                    display: none;
                    background-color: #ccc;
                    padding: 11px 10px 0;
                    border-radius: 10px;
                }
                .box {
                    top : 85px ;
                    left : 245px;
                    width:31px;
                    height:41px;
                    background-image:   url('https://cms.phavico.com/img/svg/icon_location.svg');
                    background-position: top;
                    background-repeat: no-repeat;
                    background-size: contain;
                    position: absolute; 
                }
            </style>
            </map>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'emptyText' => 'Không có bản ghi nào',
                'summary' => "<p class='summary_data'>Hiển thị {begin} - {end} trong tổng số <b>{totalCount}</b> bản ghi</p>",
                'layout'=> "{summary}\n{items}\n<div class='page-navigation'>{pager}</div>",
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn','header' => 'STT'],
                    
                    [
                        'label' => 'Loại config',
                        'value' => function ($data) {
                            if(!empty($data->type)){
                                $list_type  = Yii::$app->params['type_config'];
                                return isset($list_type[$data->type]) ? $list_type[$data->type] : '(error)';
                            }
                            return '';
                        },
                    ],
                    
                    [
                        'label' => 'Nội dung hiển thị',
                        'value' => function ($data) {
                            if(!empty($data->name)){
                                return $data->name;
                            }
                            return '';
                        },
                    ],
                    [
                        'label' => 'Link của Nội dung (nếu có)',
                        'value' => function ($data) {
                            if(!empty($data->value)){
                                return $data->value;
                            }
                            return '';
                        },
                    ],[
                        'label' => 'Vị trí/ Sắp xếp',
                        'value' => function ($data) {
                            if(!empty($data->position)){
                                return $data->position;
                            }
                            return '';
                        },
                    ],
                    [
                        'label' => 'Trạng thái',
                        'value' => function ($model) {
                            return \backend\controllers\CommonController::getStatusName($model->status);
                        },
                    ],
                    [
                        'label'=>'Icon',
                        'format' => 'raw',
                        'value' => function ($data) {
                            if(!empty($data->image)){
                                return '<img class="img-grid" src="'.$data->image.'"/>';
                            }
                            return '';
                        },
                        'contentOptions' => ['style'=>'width:200px'],
                        'enableSorting' => false,
                    ],
                    ['class' => 'yii\grid\ActionColumn',
                    'contentOptions' => ['class'=>'text-center'],
                        'template' => '{view}{update}{delete}',
                        'buttons' => [
                            'update' => function ($model, $url) use ($controller)  {
                                return '<a title="Cập nhật" style="margin:0 8px" href="/' . $controller . '/update?id=' . $url->id . '"><i class="fal fa-pencil"></i></a>';
                            },
                            // 'delete' => function ($model, $url) use ( $controller){
                            //     return '<a title="Xoá" onclick="return confirm(\'Bạn có chắc chắn muốn xoá mục này?\')" href="/' . $controller . '/delete?id=' . $url->id . '"><i class="fal fa-trash"></i></a>';
                            // }
                        ],
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.6/svg.min.js" integrity="sha256-M8IkAPnXdVChgPQwts/KeepRP4ogs+hzBtPmVhUj5YA=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/svg.connectable.js/2.0.1/svg.connectable.min.js"></script>
<script type="text/javascript" src="https://imagemap.org/js/svg.draggable.min.js"></script>
<script type="text/javascript" src="https://imagemap.org/js/svg.draw.min.js"></script>
<script type="text/javascript" src="https://imagemap.org/js/svg.select.min.js"></script>
<script type="text/javascript" src="https://imagemap.org/js/svg.resize.min.js"></script>
<script type="text/javascript" src="https://imagemap.org/js/map.min.js"></script>